theme: minima
title: SharkBuild Company & Partners
author: kid-shark
email: dks@shark.com
description: > # this means to ignore newlines until "baseurl:"
  Our company very yung but very ambitious
  we use pioneer techniques and always learn market
  and improve ourselves to be better than now

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
